name: Static Code Review

on:
  push:
    branches:
      - development

jobs:
  static-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 .
