name: Reject Pull Request if File Modified
on:
  pull_request_target:
    types: [opened, reopened]


jobs:
  check_codeowners_modification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This fetches your repository's code

      - name: Check CODEOWNERS Modification
        run: |
          BASE_COMMIT=$(git rev-parse ${{ github.event.before }})
          HEAD_COMMIT=$(git rev-parse ${{ github.sha }})

          if git diff --name-only $BASE_COMMIT $HEAD_COMMIT | grep "CODEOWNERS"; then
            echo "CODEOWNERS file has been modified. Rejecting the pull request."
            exit 1
          fi
